java.target=8
minecraft=1.12.2
forge=1.12.2-14.23.5.2864
forgegradle=3.0.197
mcp=20171003-1.12
mcp.gradle.coordinate=snapshot_20171003
gradle.forge=5.6.4
paper.api=com.destroystokyo.paper:paper-api:1.12.2-R0.1-SNAPSHOT
gradle.paper=8.4
media.capability=disabled
