license="Apache-2.0"

[[mods]]
modId="vidscreen"
version="0.1.0-SNAPSHOT"
displayName="VidScreen"
authors="VidScreen Contributors"
description='''
Synchronized in-world video screens for NeoForge clients and servers.
'''

[[dependencies.vidscreen]]
modId="neoforge"
type="required"
versionRange="[26.2.0.72,)"
ordering="NONE"
side="BOTH"

[[dependencies.vidscreen]]
modId="minecraft"
type="required"
versionRange="[26.2]"
ordering="NONE"
side="BOTH"

[[dependencies.vidscreen]]
modId="vidscreen_media_runtime"
type="required"
versionRange="[0.1.0-SNAPSHOT,)"
ordering="AFTER"
side="CLIENT"
