java.target=8
gradle.fabric=7.6.4
gradle.forge=8.4
gradle.paper=8.4
minecraft.version=1.16.5
forge.version=1.16.5-36.2.42
forgegradle.version=6.0.54
fabric.loader=0.11.7
fabric.loom=0.10.7
fabric.yarn=1.16.5+build.10:v2
fabric.api=0.42.0+1.16
paper.api=com.destroystokyo.paper:paper-api:1.16.5-R0.1-SNAPSHOT
